/* Generated By:JavaCC: Do not edit this line. PassParserConstants.java */
package com.shop.alipay.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PARAM = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DIGIT = 6;
  /** RegularExpression Id. */
  int DOLLAR = 7;
  /** RegularExpression Id. */
  int QUOTE = 8;
  /** RegularExpression Id. */
  int OTHER = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<PARAM>",
    "<LETTER>",
    "<DIGIT>",
    "<DOLLAR>",
    "<QUOTE>",
    "<OTHER>",
  };

}
